// <auto-generated />
using System;
using AFYAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AFYAPI.Migrations
{
    [DbContext(typeof(AFYContext))]
    [Migration("20190808143139_start")]
    partial class start
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AFYAPI.Models.AFYRole", b =>
                {
                    b.Property<int>("AFYRoleId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("RoleIndex");

                    b.Property<string>("RoleName");

                    b.HasKey("AFYRoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AFYAPI.Models.AFYUser", b =>
                {
                    b.Property<int>("AFYUserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("AFYUserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AFYAPI.Models.AFYUserRole", b =>
                {
                    b.Property<int>("AFYUserRoleId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("RoleAFYRoleId");

                    b.Property<int?>("UserAFYUserId");

                    b.HasKey("AFYUserRoleId");

                    b.HasIndex("RoleAFYRoleId");

                    b.HasIndex("UserAFYUserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("AFYAPI.Models.AFYUserRole", b =>
                {
                    b.HasOne("AFYAPI.Models.AFYRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleAFYRoleId");

                    b.HasOne("AFYAPI.Models.AFYUser", "User")
                        .WithMany()
                        .HasForeignKey("UserAFYUserId");
                });
#pragma warning restore 612, 618
        }
    }
}
